MENHIR = menhir
CAMLLEX = $(CAMLBIN)ocamllex

%.ml :  %.mll
	$(CAMLLEX) $<

%.ml %.mli :  %.mly
	$(MENHIR) $<

.PHONY: plugins/plugins_datacert.mlpack.d
plugins/plugins_datacert.mlpack.d : plugins/sql_parser/sql_parser.ml plugins/sql_parser/sql_lexer.ml

clean::
	rm -f */*/.*.aux */*/*/.*.aux plugins/sql_parser/sql_lexer.ml plugins/sql_parser/sql_parser.ml plugins/sql_parser/sql_parser.mli

INSTALLDEFAULTROOT=SQLFS
